POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "YYY",
  "tel" : "02-1234-5678",
  "address" : "서울 서대문구"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderID" : "44f50cfb-8bb3-43aa-ac12-b74af62d1dee"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountID" : "ec88db11-171d-427d-9d16-122daf8660cf",
  "holderID" : "60ca3def-97c5-4cb5-a25a-d8e430f8001c",
  "amount" : 500
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountID" : "91606499-2d8e-4581-9a61-8a16f4b901c1",
  "holderID" : "bff9c9ca-460f-4f7d-a2cc-b0573c988ff9",
  "amount" : 465
}

###

POST http://localhost:9090/reset

### 제주
POST localhost:9091/account
Content-Type: application/json

{
  "accountID" : "test",
  "balance" : 100
}

### command 에서 jeju 이체
POST http://localhost:8080/transfer
Content-Type: application/json

{
"srcAccountID" : "test",
"dstAccountID" : "4ab454d1-89a1-4266-9359-3c885620e74c",
"amount" : 50,
"bankType" : "JEJU"
}